# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: datingAppNotify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  send_mail:
    runs-on: windows-latest
    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MKHAS_GMAIL_USERNAME}}
        password: ${{secrets.MKHAS_GMAIL_PASSWORD}}
        subject: Github Actions job result
        # Literal body:
        body: Build job of ${{github.repository}} completed successfully!
        to: mha61@mail.aub.edu
        from: mkhas313@gmail.com
